# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

general:
  branches:
    only:
      - master # list of branches to build
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.2.1
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn test
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.2.1
    working_directory: /tmp/my-project
    steps:
      - checkout
      - run: yarn install
      - add_ssh_keys:
          fingerprints:
            - "a9:14:20:1c:70:cb:84:89:01:5e:53:35:06:fe:01:58"
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - setup_remote_docker
      - run:
          name: Start docker build and save
          command: docker build -f /tmp/my-project/Dockerfile.static -t howdryami:$CIRCLE_BRANCH .
      - run:
          name: Save docker to tar
          command: docker save -o /tmp/my-project/built-image.tar howdryami:$CIRCLE_BRANCH
  deploy:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.2.1
    working_directory: /tmp/my-project
    steps:
      - setup_remote_docker
      - run:
          name: Load saved docker file
          command: docker load < docker-cache/built-image.tar
      - run:
          name: Log in to docker hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run:
          name: Push docker file to docker hub
          command: docker push terjeofnorway/howdryami:$CIRCLE_BRANCH
      - run: ssh-keyscan 46.101.175.155 >> ~/.ssh/known_hosts
      - run: ssh-keyscan howdryami.deploythenscotch.com >> ~/.ssh/known_hosts
      - run: bash ./dockerstart.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
  docker_build_and_deploy:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
            - test
