const STORAGE_KEY = 'HOWDRYAMI.DEPLOYTHENSCOTCH';
const GENDER_CONSTANT = {
  MALE: 0.68,
  FEMALE: 0.55,
  TRANS: 0.615,
};
const BAC_BURNDOWN = 0.015;

export { STORAGE_KEY, GENDER_CONSTANT, BAC_BURNDOWN };
