const HYDRATE = 'app/ui/HYDRATE';
const LOAD_UI_DATA = 'app/ui/LOAD_UI_DATA';
const TOGGLE_DIARYEDIT_CONTAINER = 'app/ui/TOGGLE_DIARYEDIT_CONTAINER';

export {
  HYDRATE,
  LOAD_UI_DATA,
  TOGGLE_DIARYEDIT_CONTAINER,
};
