const HYDRATE = 'app/ui/HYDRATE';
const LOAD_UI_DATA = 'app/ui/LOAD_UI_DATA';
const TOGGLE_DIARYEDIT_CONTAINER = 'app/ui/TOGGLE_DIARYEDIT_CONTAINER';
const TOGGLE_CONFIRM_MODAL = 'app/ui/TOGGLE_CONFIRM_MODAL';

export {
  HYDRATE,
  LOAD_UI_DATA,
  TOGGLE_DIARYEDIT_CONTAINER,
  TOGGLE_CONFIRM_MODAL,
};
