const HYDRATE = 'app/ui/HYDRATE';
const LOAD_UI_DATA = 'app/ui/LOAD_UI_DATA';
const TOGGLE_DIARYEDIT_CONTAINER = 'app/ui/TOGGLE_DIARYEDIT_CONTAINER';
const TOGGLE_CONFIRM_MODAL = 'app/ui/TOGGLE_CONFIRM_MODAL';
const TOGGLE_DRAWER = 'app/ui/TOGGLE_DRAWER';
const UI_DATA_IS_LOADED = 'app/ui/UI_DATA_IS_LOADED';

export {
  HYDRATE,
  LOAD_UI_DATA,
  TOGGLE_DIARYEDIT_CONTAINER,
  TOGGLE_CONFIRM_MODAL,
  TOGGLE_DRAWER,
  UI_DATA_IS_LOADED,
};
