const INFLATE = 'app/user/INFLATE';
const HYDRATE = 'app/user/HYDRATE';
const REGISTER = 'app/user/REGISTER';
const CLEAR_DATA = 'app/user/CLEAR_DATA';

const USER_HYDRATION_EMPTY = 'app/user/HYDRATION_EMPTY';
const USER_HYDRATION_HAS_DATA = 'app/user/HYDRATION_HAS_DATA';

const GENDERS = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  TRANS: 'TRANS',
};

export {
  INFLATE,
  HYDRATE,
  REGISTER,
  GENDERS,
  CLEAR_DATA,
  USER_HYDRATION_EMPTY,
  USER_HYDRATION_HAS_DATA,
};
