const HYDRATE_DIARY = 'app/diary/HYDRATE_DIARY';
const ADD_DIARY_ENTRY = 'app/diary/ADD_DIARY_ENTRY';
const DELETE_DIARY_ENTRY = 'app/diary/DELETE_DIARY_ENTRY';
const UPDATE_DIARY_ENTRY = 'app/diary/UPDATE_DIARY_ENTRY';

export {
  HYDRATE_DIARY,
  ADD_DIARY_ENTRY,
  DELETE_DIARY_ENTRY,
  UPDATE_DIARY_ENTRY,
};
